---
- name: Playbook for example with delegate_to
  hosts: all
  become: yes

  vars:
    mytext: "delegate-example"

  tasks:
  - name: Ping Test
    ping:

  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
        This is file1
        Text Line2, in file1
        Text Line3, {{ mytext }}
    delegate_to: linux1

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
        This is file2
        Text Line2, in file2
        Text Line3, {{ mytext }}

  - name: Reboot servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till servers will come up 
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      delay: 5
      timeout: 40
    delegate_to: 127.0.0.1
